#! usr/bin/bash
echo '<linearGradient
     id="linearGradient4321">
    <stop
       style="stop-color:#224058;stop-opacity:1.0;"
       offset="0"
       id="stop1" />
    <stop
       style="stop-color:#224058;stop-opacity:1.0;"
       offset="1"
       id="stop2" />
  </linearGradient>'
